spring:
  application:
    name: crawling-for-project-java

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100

  datasource:
    url: jdbc:postgresql://localhost:5432/crawling-for-project-java
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
